BUNDLE_NAME = KeyboardGlassPreferences
KeyboardGlassPreferences_FILES = KGRootListController.m
KeyboardGlassPreferences_FRAMEWORKS = UIKit
KeyboardGlassPreferences_INSTALL_PATH = /Library/PreferenceBundles
KeyboardGlassPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
